data_config: 'exp_2'
model: 'CMamba_exp2'

name: 'CMamba_exp5'
max_epochs: 200
use_volume: True
additional_features: []
window_size: 14
save_checkpoints: True
batch_size: 512

hyperparams:
    optimizer: 'adam'
    lr: 0.01
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.001