data_config: 'exp_1'
model: 'CMamba_exp3'

name: 'CMamba_exp3'
max_epochs: 200
use_volume: True
additional_features: []
save_checkpoints: True
batch_size: 512

hyperparams:
    optimizer: 'adam'
    lr: 0.01
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.001